
[server]
address = "0.0.0.0"
port = 5000
headless = true
enableCORS = false
enableWebsocketCompression = false
enableXsrfProtection = false
enableStaticServing = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#00BCD4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F5F5"
textColor = "#004B54"

[ui]
hideTopBar = true

[client]
toolbarMode = "minimal"
showErrorDetails = false

[global]
developmentMode = false

[browser.gatherUsageStats]
enabled = false

[server.baseUrlPath]
value = ""

[browser.serverAddress]
value = "0.0.0.0"

[server.enableXsrfProtection]
value = false

[server.enableCORS]
value = false

[theme.base]
value = "light"
