[server]
address = "0.0.0.0"
port = 5000
headless = true
enableCORS = false
enableWebsocketCompression = false
enableXsrfProtection = false
enableStaticServing = true
baseUrlPath = "https://chattanooga.vote"

[browser]
gatherUsageStats = false
serverAddress = "chattanooga.vote"

[theme]
primaryColor = "#00BCD4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F5F5"
textColor = "#004B54"

[ui]
hideTopBar = true

[client]
toolbarMode = "minimal"
showErrorDetails = false

[global]
developmentMode = false

[server.customMetaTags]
"og:title" = "Chattanooga City Council Elections 2025"
"og:description" = "Find your district, learn about candidates, and get voting information for the 2025 Chattanooga City Council Elections."
"og:image" = "https://chattanooga.vote/assets/social/preview.jpg"
"og:type" = "website"
"twitter:card" = "summary_large_image"
"twitter:title" = "Chattanooga City Council Elections 2025"
"twitter:description" = "Find your district, learn about candidates, and get voting information for the 2025 Chattanooga City Council Elections."
"twitter:image" = "https://chattanooga.vote/assets/social/preview.jpg"